### ISSUE TITLE
Claiming namespace [dbaeumer]

### ISSUE THREAD

**Issue by dbaeumer** [eclipse/open-vsx.org#10]
I am the owner / publisher of the extension on the VS Code market place

**Comment by spoenemann** [comment]
Hi @dbaeumer, thanks for the request! You need to log in to https://open-vsx.org before we can associate the namespace with your user account.

I updated the [Namespace Access](https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace) Wiki page and added a hint to the issue template to clarify this.

**Comment by dbaeumer** [comment]
Done.
