### ISSUE TITLE
Claiming namespace julialang

### ISSUE THREAD

**Issue by davidanthoff** [eclipse/open-vsx.org#105]
I'm one of the core devs of the Julia language extension for VS Code and I also own the `julialang` publisher on the VS Code marketplace. We want to start publishing the Julia extension to open-vsx as part of our CI setup.

@appelgriebsch I believe you published a version of the extension previously? Are you ok if we take publishing over?

**Comment by appelgriebsch** [comment]
Sure. Please go ahead. I just wanted to have it available in my VSCodium when they suddenly switched to openvsx.

**Comment by davidanthoff** [comment]
We have the CI side of things ready to go, if anyone is interested: https://github.com/julia-vscode/julia-vscode/pull/1534. So once we merge this, the extension should automatically be published to open-vsx whenever we release a version.
