### ISSUE TITLE
Claiming namespace [Prisma]

### ISSUE THREAD

**Issue by carmenberndt** [eclipse/open-vsx.org#112]
Hi there,

I work at [Prisma](https://www.prisma.io/) and would like to claim exclusive rights to publish into the `Prisma` namespace.

The official Prisma extensions on the Marketplace:
- https://marketplace.visualstudio.com/items?itemName=Prisma.prisma
- https://marketplace.visualstudio.com/items?itemName=Prisma.prisma-insider

This is the issue to publish our extension to open-vsx: https://github.com/prisma/language-tools/issues/349

**Comment by spoenemann** [comment]
Done. The warnings on https://open-vsx.org/extension/Prisma/prisma-insider and https://open-vsx.org/extension/Prisma/vscode-graphql will go away after you have published new versions of those extensions yourself.

**Comment by carmenberndt** [comment]
Thanks! 🚀
