### ISSUE TITLE
Claiming namespace haskell

### ISSUE THREAD

**Issue by jaspervdj** [eclipse/open-vsx.org#115]
Hi maintainers,  I am the [current Chair of the Haskell.org committee](https://wiki.haskell.org/Haskell.org_committee#Current_members).  As discussed in https://github.com/haskell/vscode-haskell/issues/250, I would like to claim the `haskell` namespace.  It seems that it already exists but we don't know the current owner.  If their extensions are Haskell-related, I'd be happy to let them continue using the namespace as well.

**Comment by spoenemann** [comment]
Although, the namespace has been created before, it does not contain any extensions yet: https://open-vsx.org/api/haskell

You can now add more owners or contributors yourself in https://open-vsx.org/user-settings/namespaces

**Comment by jaspervdj** [comment]
Thanks for the quick turnaround!
