### ISSUE TITLE
Claiming namespace Luxcium

### ISSUE THREAD

**Issue by Luxcium** [eclipse/open-vsx.org#127]
## Claiming namespace uppercase «L» Luxcium 
**This request is for Uppercase «L» and the lowercase equivalent of Luxcium**

I am the owner of [Luxcium/pop-n-lock-theme-vscode](https://github.com/Luxcium/pop-n-lock-theme-vscode) on Git Hub
I am the owner of the npm package [pop-n-lock-theme-vscode](https://www.npmjs.com/package/pop-n-lock-theme-vscode)
I am the owner of npm org [luxcium](https://www.npmjs.com/org/luxcium) 
I go by Luxcium on twitter [@Luxcium](https://twitter.com/Luxcium)
I am the owner of [Luxcium.pop-n-lock-theme-vscode](https://marketplace.visualstudio.com/items?itemName=Luxcium.pop-n-lock-theme-vscode) in Visual Studio's marketplace  
And well on git hub also @Luxcium
I am the owner of the publisher account [Luxcium](https://marketplace.visualstudio.com/publishers/Luxcium) on Visual Studio's marketplace  
**Edit:**
I am registred as https://gitlab.com/Luxcium
I am using also on https://medium.com/@Luxcium

[The namespace Luxcium is public, which means that everyone can publish new versions of the “Pop N' Lock Theme by Luxcium ✨” extension. If you would like to become the owner of Luxcium, please read this guide.](https://open-vsx.org/extension/Luxcium/pop-n-lock-theme-vscode/reviews)

**Comment by spoenemann** [comment]
Hi @Luxcium, you need to log in to https://open-vsx.org once before I can grant the namespace.

**Comment by Luxcium** [comment]
> Hi @Luxcium, you need to log in to https://open-vsx.org once before I can grant the namespace.

Done  !!! I also have generated a new token which I am not sure what it could be usefull for `27d!!!!!-!@!!-!!@@-!@@!-!!!!!b173d14`

**Comment by spoenemann** [comment]
>  I also have generated a new token which I am not sure what it could be usefull for

Is that the generated token value? If so, you should keep it secret. You can revoke leaked tokens on https://open-vsx.org/user-settings/tokens.

**Comment by Luxcium** [comment]
> > I also have generated a new token which I am not sure what it could be usefull for
> 
> Is that the generated token value? If so, you should keep it secret. You can revoke leaked tokens on https://open-vsx.org/user-settings/tokens.

I obviously put `!!!!!!!`'s instead of the actual token and was asking more about the places that require this token?

**Comment by Luxcium** [comment]
All is now working I followed the instruction to upload the latest version of my package to https://open-vsx.org/extension/Luxcium/pop-n-lock-theme-vscode my token is safe and I used the real one to upload the latest version of `Pop N' Lock Theme by Luxcium ✨`

**Comment by spoenemann** [comment]
> I obviously put !!!!!!!'s instead of the actual token and was asking more about the places that require this token?

:grin: Ok I didn't get the question right. I guess you found the instructions on https://github.com/eclipse/openvsx/wiki/Publishing-Extensions now.

**Comment by Luxcium** [comment]
OOPS ??? 

![Screenshot_20210718_231439](https://user-images.githubusercontent.com/42672814/126097472-be9f217d-9623-4fa1-97eb-c3f2225fd3fe.png)

**Comment by Luxcium** [comment]
New Edit: (as of #591)
I am using https://dev.to/luxcium

**Comment by Luxcium** [comment]
Eclipse Foundation, Inc.

Open VSX Publisher Agreement
Thank you for your interest in publishing in the Eclipse Open VSX Registry (“Open VSX”). As used in this Eclipse Open VSX Publisher Agreement (“Agreement”), the term “you”, ”your” or “Publisher” refers to you as an individual, and, to the extent you are the agent or employee of another person or entity that has rights in the Offering (as defined below) (such person or entity, a “Principal”) “you” and “publisher” also includes that Principal.

This Agreement describes the relationship between you and the Eclipse Foundation, Inc. (“Eclipse”, “us” or “we”) and governs your publication of any Offering (as defined below) within the Registry (as defined below).

By clicking where indicated to accept this Agreement, the individual entering into this Agreement represents and warrants to Eclipse that such individual has the authority to enter into this Agreement (including on behalf of his or her Principal), and you (including such individual and any Principal) agree to be bound by its terms.

SECTION 1 Definitions.
a. “Code Content” shall have the meaning set forth in the Eclipse Intellectual Property Policy.

b. “Content” shall have the meaning set forth in the Eclipse Intellectual Property Policy.

c. “Listing Information” means: (i) the information and images accompanying an Offering that identifies the original source of the Offering, as well as the nature and other features of the Offering, as specified by you in connection with your request to publish the Offering; and (ii) to the extent applicable, Data Information (as defined herein).

d. “Non-Code Content” shall have the meaning set forth in the Eclipse Intellectual Property Policy.

e. “Offering” means any software, data, media, documentation, etc. published or proposed to be published in the Registry under this Agreement.

f. “Offering Contents” means all data and software included within, installable by, or otherwise associated with an Offering. Offering Contents include, without limitation, all operating system and application software associated with an Offering.

g. “Publisher Account” means a publisher account for Open VSX, which includes a username and password.

h. “Registry” means a limited, Eclipse Hosted repository of Offerings published to Open VSX.

i. “Terms of Use” means the Eclipse.org Terms of Use, the legal terms under which you grant others the right to use or access your Offering, as well as all Offering Contents associated therewith, as specified in the Listing Information associated with your Offering.

j. All other capitalized terms that are not defined in this Section 1 shall have the meanings assigned in the text of this Agreement.

SECTION 2 Publisher Account.
Your Publisher Account is only for your use, and you are responsible for all activity that takes place within your Publisher Account. If you fail to keep your Publisher Account in good standing (for example by providing incorrect or outdated information, by engaging in dishonest or fraudulent activity, or by repeatedly submitting Offerings that violate this Agreement, abuse the Registry or interfere with any other party’s use of the Registry), we may revoke your Publisher Account, remove your Offerings from the Registry, delete Offering ratings and reviews, and pursue any other remedies available to us.

SECTION 3 Submission, Approval, and Publication of Offerings.
a. Submission Process. You must submit a request for each Offering that you wish to publish in the Registry. We may approve or reject any proposed Offering in our sole discretion, and may condition our approval on your making modifications to the Offering or its Listing Information. You are responsible for ensuring that the Listing Information associated with your Offering is accurate and not misleading and does not violate third parties’ intellectual property rights, including third-party trademarks or icons. We may require you to provide us with one or more Offering prototypes. Following our approval of an Offering, you may publish the Offering in the Registry, subject to the terms and conditions of this Agreement and the Listing Information provided with your request. Publications of any Offering in the Registry is subject to this agreement being executed and being in effect at the time of publication.

b. Presentation of Offerings. We reserve the right to determine the manner in which all Offerings, whether published by you or others, are presented and promoted in the Registry. We may display your Listing Information in connection with your Offering, as well as other information designed to inform that the Offering is provided by you, including what content is included within the Offering. Notwithstanding our approval of an Offering as described in Section 3(a) above, we, in our sole discretion may determine not to make an Offering available in the Registry.

c. Ratings and Reviews. You understand that as part of the Registry, we may make available a facility for third parties to post ratings and reviews on your Offering (“Reviews”). You understand that while we may (but are not obligated to) exercise traditional editorial functions associated with such Reviews, we have no obligation to, and shall not be, reviewing, vetting, or otherwise examining such Reviews and have no obligation to remove Reviews that may be unfavorable to your Offering.

d. Terms for Publisher Marks. You hereby grant us a non-exclusive, royalty-free, personal license to display the trademarks and logos associated with the Offering (“Publisher Marks”), as provided to us in connection with the marketing and promotion of your Offerings in the Registry. You represent and warrant that you are the owner and/or authorized licensor of the Publisher Marks. As between the parties, all goodwill associated with the Publisher Marks shall inure to your benefit. We may reformat or resize Publisher Marks as necessary and without altering the overall appearance of the Publisher Marks.

e. No Compensation. You expressly acknowledge that neither Eclipse nor any licensee or end-user of any of your Offerings published on the Registry shall be required to provide you with any compensation for the distribution or use of your Offering as made available on the Registry.

SECTION 4 Licensing of Offerings and Support
a. Licensing of Offerings. All Registry Content Offerings must be licensed. You are responsible for ensuring that you have all necessary rights to make your Offering available under the license you have stipulated. Any Content submitted by Publisher where Publisher has not specified a license will be made available under the MIT license, and you are responsible to ensure that you have the necessary rights to permit that. Such licenses and grants will be between you and licensees and end users and will not create any obligations or responsibilities of any kind for Eclipse. Subject to the terms of this Agreement, you are solely responsible for implementing any technical or security features designed to prevent unauthorized access to or use of your Offerings.

b. Support. You are responsible for any support of your Offerings.

c. Enforcement/Monitoring. We are not responsible for monitoring the use of your Offering, for reporting to you with respect to such use, preventing the inappropriate use of your Offering or for enforcing your intellectual property rights in and to your Offering. Eclipse expressly disclaims any obligation to do any of the foregoing.

SECTION 5 Privacy and Data Protection.
To the extent that you collect any data regarding the use of your Offering, including without limitation any information regarding the licensee or end-user of the Offering, you shall disclose in your Listing Information for the Offering a full and complete description of what data you collect, for what purposes it is used, with whom it is shared and how long it is retained (“Data Information”). Without limitation of the foregoing, you agree to comply with all applicable data protection and privacy laws, regulations and ordinances relevant to the use of your Offering.

SECTION 6 Removal of Offerings.
We reserve the right to elect not to make an Offering available on the Registry or to remove or suspend the availability of any Offering from the Registry for any reason or no reason. Reasons may include, without limitation, (i) your breach of the terms of this Agreement; (ii) your express termination of this Agreement; (iii) inconsistency between your Offering and its Listing Information; (iv) an assertion or claim that your Offering infringes the intellectual property rights of a third party; or (v) complaints or concerns about the content or quality of your Offering. We reserve the right to discontinue the availability of the Registry at any time and without notice to you.

SECTION 7 Warranties.
You represent, warrant, and undertake to Eclipse that:

a. Your Offering does not collect any information not fully disclosed in the Listing Information and does not contain any malware or other malicious code, inappropriate content, or material, the creation, possession, distribution or use of is in violation of any law, regulation or ordinance;

b. Your Listing Information associated with the Offering is not misleading and is a substantially accurate and complete description of the performance, data collection functions and other characteristics of the Offering;

c. You have obtained any and all consents, approvals, or licenses (including written consents of third parties where applicable) and have all rights required for you to make your Offerings available in the Registry;

d. Our exercise of the rights granted by you under this Agreement will not obligate us to pay any third-party amounts;

e. Information that you provide to us under or in connection with this Agreement is true, accurate, current, and complete; and

f. In carrying out your obligations set forth in this Agreement, you are in compliance with all applicable laws, including privacy laws.

SECTION 8 Disclaimer, Limitation of Liability, and Defense of Claims.
a. DISCLAIMER OF WARRANTY. WE PROVIDE THE REGISTRY “AS-IS,” “WITH ALL FAULTS,” AND “AS AVAILABLE.” YOU BEAR THE RISK OF PUBLISHING YOUR OFFERINGS THROUGH THE REGISTRY FOR USE BY LICENSEES AND END USERS. TO THE EXTENT PERMITTED BY APPLICABLE LAW, WE EXCLUDE ANY IMPLIED WARRANTIES OR CONDITIONS, INCLUDING THOSE OF PRODUCT LIABILITY, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, WORKMANLIKE EFFORT, AND NON-INFRINGEMENT RELATING TO OPEN VSX WITHOUT LIMITING THE FOREGOING, WE EXPRESSLY DISCLAIM ANY WARRANTIES THAT ACCESS TO, OR USE OF, THE REGISTRY WILL BE UNINTERRUPTED OR ERROR FREE.

b. Limitation of Liability. TO THE EXTENT PERMITTED BY APPLICABLE LAW, ECLIPSE SHALL NOT HAVE ANY LIABILITY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING WITHOUT LIMITATION LOST PROFITS), HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OR DISTRIBUTION OF THE OFFERING OR THE EXERCISE OF ANY RIGHTS GRANTED HEREUNDER, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

c. Duty to Defend. You agree to defend, indemnify, and hold harmless us, Eclipse members, agents, officers, directors and employees as applicable, from and against any costs, losses, damages, liabilities or expenses and attorneys’ fees arising from any and all third-party claims alleging that your Offering, including any Listing Information, infringes any proprietary or personal right of a third party; or arising from any dispute between you and a licensee or End User of your Offering, relating to your Offering.

SECTION 9 Term and Termination.
a. General. This Agreement will remain in effect until terminated. Either party may terminate this Agreement at any time, for any reason or no reason, upon thirty (30) days’ written notice and removal of all of your Offerings from the Registry.

b. Effect of Termination. Sections of this Agreement that, by their terms, require performance or establish rights or protections after the termination or expiration of this Agreement will survive.

SECTION 10 Miscellaneous
a. Notices. All notices that you provide to us under this Agreement must be sent to the following email alias: license@eclipse.org.

b. No Exclusivity. Each party acknowledges and agrees that the rights granted to and obligations due to the other party in this Agreement are intended to be non-exclusive, and therefore that nothing in this Agreement will be deemed or construed to prohibit either party from engaging in or participating itself or with one or more third parties in business arrangements similar to or competitive with those described herein.

c. Jurisdiction and Governing Law. This Agreement will be governed by the laws of the State of New York without reference to conflict of laws principles.

d. Responding to Claims. If we receive a claim from a third party requesting that your Offering be changed or removed, we may refer that claim to you. If you believe that your Offering may be in violation of the terms of this Agreement, you must immediately notify us and work with us to cure the violation.

e. Waiver. Either party’s delay or failure to exercise any right or remedy will not result in a waiver of that or any other right or remedy

f. Severability. If any court of competent jurisdiction determines that any provision of this Agreement is illegal, invalid, or unenforceable, the remaining provisions will remain in full force and effect.

g. Assignment. Except as provided for below in this paragraph, neither party may assign this Agreement (or any rights or duties under it) without the other party’s prior written consent, provided that either party may assign this Agreement without the other party’s consent in connection with a merger, acquisition, or sale or transfer of all or substantially all of its assets, excepting that Eclipse may assign this agreement to any entity that serves as a successor steward to the Registry. Either party who assigns this Agreement as permitted in this Section 10(g) shall provide the other party with prompt notice of such assignment. Subject to the foregoing, this Agreement will be binding upon and inure to the benefit of the parties and their permitted successors and assigns.

h. English Language. The parties intend for this Agreement to be written and interpreted solely in English. Any notices required or provided under this Agreement will be in English. In the event of any conflict between the English version of this Agreement or any notices and a translation of the same, the English version will prevail.

i. Relationship of Parties. Neither this Agreement, nor any terms and conditions contained herein, create a partnership, joint venture, employment relationship, or grant of any rights.

j. Updates. We may update this Agreement from time to time. By continuing to make Offerings available in the Registry, you agree to be bound by the terms and conditions contained in the updated Agreement.

k. Entire Agreement. This Agreement constitutes the entire agreement between the parties with respect to the subject matter hereof and supersedes all prior and contemporaneous communications.
