### ISSUE TITLE
Claiming namespace Ionide

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [eclipse/open-vsx.org#134]
I'm an owner of Ionide GH organization (https://github.com/ionide) and VSCode publisher (https://marketplace.visualstudio.com/publishers/Ionide).

Additionally, could you also add @baronfel as an owner of this namespace?

**Comment by spoenemann** [comment]
I cannot add @baronfel because he needs to log in to https://open-vsx.org first. But you can now manage namespace members yourself at https://open-vsx.org/user-settings/namespaces

**Comment by Krzysztof-Cieslak** [comment]
Thanks!
