### ISSUE TITLE
Move extension between publishers/namespaces

### ISSUE THREAD

**Issue by daimor** [eclipse/open-vsx.org#136]
I'm the author of the extension 
https://open-vsx.org/extension/daimor/vscode-objectscript/
Repository
https://github.com/intersystems-community/vscode-objectscript
And now while it's getting wider support, we are decided to move to another namespace
It's already done by VSCode Marketplace support. And we need the same here
https://marketplace.visualstudio.com/items?itemName=intersystems-community.vscode-objectscript

So, we need to replace `daimor` with `intersystems-community` for this particular extension.
I did not found a way, how to unpublish my extension, so I need your help with it.
`intersystems-community` namespace already exists and claimed by @rajrsingh

**Comment by spoenemann** [comment]
So you would like to delete `daimor.vscode-objectscript` and encourage everyone to use `intersystems-community.vscode-objectscript` instead? Wouldn't it make sense to deprecate the old extension first? E.g. you could publish a new version on the old namespace where the README explains the namespace shift.

**Comment by daimor** [comment]
VSCode marketplace managed to rename extension Id. So, everyone who already installed previous one, don’t do anything to install new one, it’s just updates with new id. As we don’t have now old id in VSCode Marketplace I would expect the same in Open VSX

**Comment by spoenemann** [comment]
You can just publish the extension in the new namespace and then I can delete the old extension, but then VSCodium users would not be able to auto-update to the new extension. Updating the extension id is rather complex at the moment. I've raised https://github.com/VSCodium/vscodium/issues/494 to improve this.

**Comment by daimor** [comment]
It's ok, I let you know when it will be ready for deletion.

**Comment by spoenemann** [comment]
Hi @daimor what's the current state here? Shall I delete `daimor.vscode-objectscript`?

**Comment by daimor** [comment]
Hi, sorry, forgot about it, yes, it's ready to be deleted

**Comment by spoenemann** [comment]
Done.
