### ISSUE TITLE
Removing Extension Requirement

### ISSUE THREAD

**Issue by zhanghua000** [eclipse/open-vsx.org#138]
I am the maintainer of `zhanghua.vscode-language-pack-zh-cn`, I made a mistake when upgrading this extension, I made a wrong spell of the plugin id and I published it accidently. I hope to remove it. The right id is `zhanghua.vscodium-language-pack-zh-cn` and I have upgraded it. Sorry to make this trouble.

**Comment by spoenemann** [comment]
Deleted.
