### ISSUE TITLE
Claiming namespace webfreak

### ISSUE THREAD

**Issue by WebFreak001** [eclipse/open-vsx.org#140]
Hi I would like to claim the namespace `webfreak` for publishing the plugins I am also publishing on the vscode marketplace ([webfreak.code-d](https://marketplace.visualstudio.com/items?itemName=webfreak.code-d))

Repo: https://github.com/Pure-D/code-d

I also just noticed you are publishing my other plugin (https://open-vsx.org/extension/webfreak/debug) through open-vsx, should that stay there or also be managed by me instead? I'm not doing releases of that extension often but when I do, I can also push it to open-vsx

**Comment by spoenemann** [comment]
I disabled automatic publishing of `webfreak.debug`. It would be great if you could take over publishing that extension, too.
