### ISSUE TITLE
Claiming namespace muhammad-sammy

### ISSUE THREAD

**Issue by muhammadsammy** [eclipse/open-vsx.org#143]
my personal namespace.

**Comment by muhammadsammy** [comment]
Hey, @spoenemann!
This namespace is no longer granted for my account.
Would you please verify my account with this namespace?

**Comment by spoenemann** [comment]
Hi @muhammadsammy, for reasons I do not understand your namespace membership was changed to `contributor`. I changed it back to `owner`.

**Comment by muhammadsammy** [comment]
Thanks! :smile:
