### ISSUE TITLE
Claiming namespace bceskavich

### ISSUE THREAD

**Issue by bceskavich** [eclipse/open-vsx.org#165]
I'm the owner/maintainer of the [Dracula At Night](https://github.com/bceskavich/dracula-at-night) theme, which is [now live](https://open-vsx.org/extension/bceskavich/theme-dracula-at-night) on the Open VSX Marketplace (see https://github.com/open-vsx/publish-extensions/pull/172).

I'd like to claim ownership of the associated namespace `bceskavich` on Open VSX as a result.

**Comment by spoenemann** [comment]
Hi @bceskavich! You need to log in to https://open-vsx.org/ before I can assign you as owner of the namespace.

Would you also like to take over publishing of the extension? If you publish yourself, the extension will be shown with a "verified" symbol like here: https://open-vsx.org/extension/armandphilippot/coldark
It is possible to continue publishing via the `publish-extensions` script (done by the @open-vsx bot) after assigning the namespace to you, but then the extension is shown with a warning symbol like here: https://open-vsx.org/extension/ms-vscode/node-debug2

**Comment by bceskavich** [comment]
@spoenemann Ah got it. I just logged in. Also yes, I can take ownership of publishing to Open VSX. Is there a guide you could share on how to do so?

**Comment by spoenemann** [comment]
Yes, there's a guide here:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
