### ISSUE TITLE
Communication on Upcoming open-vsx.org Changes to Prepare Publishers

### ISSUE THREAD

**Issue by brianking** [eclipse/open-vsx.org#185]
We need to publish a post to communicate upcoming changes and detail action that publishers need to take to prepare. We should consider addressing the other audiences in the post, namely users and publishers.

Working document:
https://docs.google.com/document/d/1fclmLWK9yu0HaNFl6AJeCrcoETfR3oRmm7BUNq5VLTo/edit?usp=sharing

**Comment by brianking** [comment]
This is finished, however we are waiting on one final thing before it can be published. It is the publisher agreement, that we want to link to.

**Comment by brianking** [comment]
Transition post is now live:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management

@spoenemann @jbicker The banner post can now go live on open-vsx.org.

Text:
This website will be transferred to the Eclipse Foundation on December 9. Please read [this blog post](https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management) to find out more. If you are a publisher, some action will be required.

**Comment by spoenemann** [comment]
@brianking the blog post says December 8.

**Comment by brianking** [comment]
I've fixed the date in the post. Correct date is Dec 9.

**Comment by spoenemann** [comment]
The banner is rolled out.

**Comment by brianking** [comment]
I wonder if it should have a different background colour than the sections above and below? A darker colour would make it stand out more.

**Comment by spoenemann** [comment]
Made the background blue and added an info icon.
