### ISSUE TITLE
Claiming namespace RokuCommunity

### ISSUE THREAD

**Issue by TwitchBronBron** [eclipse/open-vsx.org#196]
I'm the owner of the [RokuCommunity github organization](https://github.com/rokucommunity). I maintain the [BrightScript Language vscode extension](https://marketplace.visualstudio.com/items?itemName=celsoaf.brightscript). I was recently asked to publish our extension to `open-vsix.org` in [this](https://github.com/rokucommunity/vscode-brightscript-language/issues/283) github issue, so that's what I'm trying to do. :)

**Comment by spoenemann** [comment]
Hi @TwitchBronBron! It seems the [RokuCommunity](https://marketplace.visualstudio.com/publishers/celsoaf) publisher uses the publisher id `celsoaf`. Open VSX does not support publisher names at the moment, but only publisher ids. Is it ok to change this request to the namespace `celsoaf`?

**Comment by TwitchBronBron** [comment]
No, I'd prefer to keep it as "RokuCommunity". `celsoaf` was the original creator of the extension, but we have grown into a full organization at this point and would like to keep the "RokuCommunity" brand moving forward for everything. I already sent an email to the Visual Studio Extension Store team about changing the publisher ID for the extension as well.

**Comment by spoenemann** [comment]
Ok, I created the namespace `RokuCommunity` and assigned it.
