### ISSUE TITLE
Claiming namespace [pivotal]

### ISSUE THREAD

**Issue by martinlippert** [eclipse/open-vsx.org#2]
We would like to publish our extensions to the marketplace around Spring under the `pivotal` namespace.

**Comment by kdvolder** [comment]
Are namespaces case sensitive? Because the name of our 'publisher' in vscode extension package.json file is actually 'Pivotal' not 'pivotal'. 

See for example: 

https://github.com/spring-projects/sts4/blob/master/vscode-extensions/vscode-concourse/package.json#L7

**Comment by kdvolder** [comment]
Okay, yeah, so indeed looks like it is case sensitive. I had to create a new namespace called `Pivotal` to be able to publish our extensions. So it looks like the namespace `pivotal` that @martinlippert already created before is considered as a different namespace.

Our extensions latest versions are now published and can be found here:

https://open-vsx.org/?search=Pivotal

**Comment by spoenemann** [comment]
Namespaces are _not_ case sensitive.

@martinlippert @kdvolder shall I set you both as owners of `Pivotal` and `VMware` (#3)?

**Comment by spoenemann** [comment]
@martinlippert you need to log in to https://open-vsx.org once before you can become an owner of a namespace.

**Comment by martinlippert** [comment]
> @martinlippert @kdvolder shall I set you both as owners of `Pivotal` and `VMware` (#3)?

Yes, please... :-)

> @martinlippert you need to log in to https://open-vsx.org once before you can become an owner of a namespace.

Done.

**Comment by martinlippert** [comment]
Awesome, thanks!!!
Keep up the great work!!!
