### ISSUE TITLE
Share Transition post to publishers in the CL Tool

### ISSUE THREAD

**Issue by brianking** [eclipse/open-vsx.org#210]
Between now and December 9, alert publishers when they are adding a new extension about the requirements.

The text can be the same that is in the banner on open-vsx.org.

**Comment by spoenemann** [comment]
I slightly modified the text:

```
The open-vsx.org website will be transferred to the Eclipse Foundation on December 9. Please read the blog post referenced below to find out more. Some action will be required so you can continue publishing.
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
```

@brianking Ok?

**Comment by brianking** [comment]
Yes, this is fine.

**Comment by spoenemann** [comment]
New version of [ovsx](https://www.npmjs.com/package/ovsx) is published.
