### ISSUE TITLE
Claiming namespace ocamllabs

### ISSUE THREAD

**Issue by smorimoto** [eclipse/open-vsx.org#223]
I don't know how to explain why we are the legitimate owner of the namespace, but we are releasing an extension for the OCaml programming language from an organization called OCaml Labs. I think namespaces need to be exclusive to avoid unnecessary confusion.

https://github.com/ocamllabs/vscode-ocaml-platform

See these for information about OCaml Labs:
  - http://ocamllabs.io
  - https://ocaml.org/ocamllabs

A related issue: https://github.com/ocamllabs/vscode-ocaml-platform/issues/438

**Comment by spoenemann** [comment]
[OCaml Platform](https://open-vsx.org/extension/ocamllabs/ocaml-platform) has been published by @mnxn (see https://github.com/open-vsx/publish-extensions/pull/222). Shall I set you both as owners?

**Comment by mnxn** [comment]
You can set us both as owners. And if possible, @rgrinberg as well.

**Comment by spoenemann** [comment]
You can add more owners and contributors yourself in https://open-vsx.org/user-settings/namespaces

**Comment by smorimoto** [comment]
Thanks @spoenemann!
