### ISSUE TITLE
Claiming namespace Zowe

### ISSUE THREAD

**Issue by zFernand0** [eclipse/open-vsx.org#225]
Hello!

As a contributor to the [Zowe](https://github.com/zowe) project and maintainer of the [Zowe publisher](https://marketplace.visualstudio.com/publishers/Zowe) on the VSCode Marketplace, I wanted to ensure that we owned the namespace with the plans to continuously update the Zowe extensions in the Open VSX Registry as well as the VSCode Marketplace. Once we get ownership, we can proceed to adding automation account / bots. 

Thank you @zimlu02 for taking the initiative! : )

**Comment by spoenemann** [comment]
Done. The already published extension https://open-vsx.org/extension/Zowe/vscode-extension-for-zowe is currently shown with a warning because it was published by @zimlu02. The warning will disappear after you have published a new version yourself (or through a bot that you've added as contributor).
