### ISSUE TITLE
Claiming namespace [BroadcomMFD]

### ISSUE THREAD

**Issue by zimlu02** [eclipse/open-vsx.org#23]
I am Product Owner of Code4z project ([repo](https://github.com/eclipse/che-che4z) | [VSC Marketplace](https://marketplace.visualstudio.com/items?itemName=broadcomMFD.code4z-extension-pack)) that is being released under BroadcomMFD publisher on VSC Marketplace.

**Comment by spoenemann** [comment]
I guess you meant [this repo](https://github.com/BroadcomMFD/code4z)

**Comment by spoenemann** [comment]
What is the license of that extension? I couldn't find it in the repository.

**Comment by zimlu02** [comment]
> What is the license of that extension? I couldn't find it in the repository.

Code4z is a package of various extensions, most of them are EPL 2.0
