### ISSUE TITLE
Claiming namespace Janne252

### ISSUE THREAD

**Issue by Janne252** [eclipse/open-vsx.org#235]
I'm the author of [vscode-fontawesome-auto-complete](https://github.com/Janne252/vscode-fontawesome-auto-complete) which is published under the matching publisher name on the Visual Studio marketplace: https://marketplace.visualstudio.com/items?itemName=Janne252.fontawesome-autocomplete

At first I thought https://open-vsx.org/extension/Janne252/fontawesome-autocomplete was a mirror but apparently it has been published by @banggua.

Ideally I would also like to become the author of https://open-vsx.org/extension/Janne252/fontawesome-autocomplete and maintain it. If that can be arranged, I think it would be best to change the author _after_ [some upcoming changes in December](https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management).

**Comment by spoenemann** [comment]
Hi @Janne252! It's not possible to change the publisher of an already published extension version (version `1.0.1` in this case). The website will display you as verified publisher as soon as you publish a newer version. If you'd like to republish version `1.0.1`, I can delete the already published version. As a side effect, this would clear the download statistics of the extension.

**Comment by Janne252** [comment]
Hey @spoenemann, thanks for the quick reply. I've published the latest version `1.1.0`, worked smoothly.
