### ISSUE TITLE
Removal of  bitlang.cobol-plus-pack

### ISSUE THREAD

**Issue by spgennard** [eclipse/open-vsx.org#24]
The vsix  bitlang.cobol-plus-pack has been removed on microsoft vsx, as it is
been refactored into a [different vsix](https://open-vsx.org/extension/bitlang/cobol-themes)
that just has themes in it.

Can it be removed fromn here too?

**Comment by GitMensch** [comment]
> In the meantime, you can create an issue at https://github.com/eclipse/open-vsx.org/issues if you want an extension (or a specific version of it) to be removed.

_Originally posted by @spoenemann in https://github.com/eclipse/openvsx/issues/58#issuecomment-607902879_

Thanks for repackaging the bitlang.cobol stuff @spgennard, thanks for removing the old stuff @spoenemann

**Comment by spoenemann** [comment]
The following versions of `bitlang.cobol` have a dependency on `bitlang.cobol-plus-pack`:

6.2.34
6.2.35
6.2.36
6.2.37
6.2.38
6.2.39
6.2.40
6.2.41
6.2.42
6.2.43
6.2.44

I would have to delete these, too, in order to delete `bitlang.cobol-plus-pack`. Is that ok?

**Comment by GitMensch** [comment]
Good catch.

For me the answer is "yes", as the dependency was bad up-front https://github.com/spgennard/vscode_cobol/issues/137 and included additional dependencies.
But I don't know if someone has a need for those specific old versions (I guess not).

**Comment by spgennard** [comment]
Yes, that is perfectly fine and expected.

Thank you so much

**Comment by spoenemann** [comment]
Done.
