### ISSUE TITLE
Claiming namespace ComplYue

### ISSUE THREAD

**Issue by complyue** [eclipse/open-vsx.org#25]
This is my personal name and publisher name with VSCode marketplace, and have published 3 extensions so far.

**Comment by spoenemann** [comment]
Done.

Your extensions seem to have no LICENSE. Could you add one? In case you're unsure which one, I'd choose MIT, Apache-2.0 or EPL-2.0.

**Comment by complyue** [comment]
Thanks for reminding, added MIT
