### ISSUE TITLE
Claiming namespace [codingyu]

### ISSUE THREAD

**Issue by codingyu** [eclipse/open-vsx.org#33]
This is my username, used on many platforms, and an [extension](https://open-vsx.org/extension/codingyu/laravel-goto-view) has been released.

**Comment by spoenemann** [comment]
The Laravel goto view extension has no LICENSE. Could you add one? In case you're unsure which one, I'd choose MIT, Apache-2.0 or EPL-2.0.

**Comment by codingyu** [comment]
> The Laravel goto view extension has no LICENSE. Could you add one? In case you're unsure which one, I'd choose MIT, Apache-2.0 or EPL-2.0.

Thanks, I chose MIT, has already been updated
