### ISSUE TITLE
Remove wrong version of Context Mapper extension

### ISSUE THREAD

**Issue by stefan-ka** [eclipse/open-vsx.org#48]
Hi there

In https://github.com/eclipse/openvsx/issues/58#issuecomment-607902879 I saw that one can create an issue here, in case I want to have a version of my extension deleted. 

While testing my publication process I accidentally published a SNAPSHOT version of my Context Mapper extension:
https://open-vsx.org/extension/contextmapper/context-mapper-vscode-extension

Could you please remove the version `5.14.0-SNAPSHOT`? 

Thanks and best regards,
Stefan

**Comment by stefan-ka** [comment]
Can someone help me out here, please? The publishing tool does not allow to remove a version, right?

Would be important before people start installing this snapshot 😬

Many thanks!

**Comment by jbicker** [comment]
It is removed.

**Comment by stefan-ka** [comment]
Thank you very much @jbicker! 🙏
