### ISSUE TITLE
Claiming namespace [webhint]

### ISSUE THREAD

**Issue by molant** [eclipse/open-vsx.org#52]
I'm one of the [core maintainers of webhint](https://github.com/orgs/webhintio/people?query=role%3Aowner).

In [today's meeting](https://github.com/webhintio/hint/issues/3843#issuecomment-650287988) we decided to publish our extension to Open VSX as well per a request done by @entepe85 in https://github.com/webhintio/hint/issues/3831

Webhint is an OpenJS Foundation project and the brand is trademarked. We would like to have ownership of this namespace to prevent any issues.

Thank you

**Comment by jbicker** [comment]
Added molant as owner of webhint
