### ISSUE TITLE
Claiming namespace [redhat]

### ISSUE THREAD

**Issue by fbricon** [eclipse/open-vsx.org#6]
I'm a Red Hat employee, already publishing several extensions on the VS Code Marketplace: https://marketplace.visualstudio.com/publishers/redhat

**Comment by fbricon** [comment]
Could you also add @Gorkem as co-owner please?

**Comment by spoenemann** [comment]
@fbricon I set you as owner, but @gorkem needs to log in to https://open-vsx.org once before I can add him, too.

**Comment by fbricon** [comment]
@spoenemann thanks. Can you please also add @apupier?

**Comment by spoenemann** [comment]
✅

Still cannot find @gorkem in the database.

**Comment by spoenemann** [comment]
(Note: as soon as https://github.com/eclipse/openvsx/issues/5 is implemented, you'll be able to add more owners / contributors yourself)

**Comment by gorkem** [comment]
@spoenemann I have logged in
