### ISSUE TITLE
About page link gives a 404

### ISSUE THREAD

**Issue by axelson** [eclipse/open-vsx.org#70]
This should render the about page but instead a 404 (with a missing error page) is rendered instead:
https://open-vsx.org/about

**Comment by GitMensch** [comment]
That's happening similar for some plugins, see https://open-vsx.org/vscode/gallery/publishers/bitlang/vsextensions/cobol/6.5.3/vspackage.
The actual file download and about page for this plugin does work; the vspackage entry, which seems to be used by the store api, worked before - as did the about page.

**Comment by jbicker** [comment]
https://open-vsx.org/about works now.

**Comment by GitMensch** [comment]
Yes. @jbicker do you think the other page has the same issue - whatever "about" had - or a different one?

**Comment by jbicker** [comment]
I am looking into it.

**Comment by jbicker** [comment]
@GitMensch how (or where) did you get that URL?

**Comment by GitMensch** [comment]
vscodium -> search for extensions -> cobol.bitlang: install latest -> error during install -> install manually
Is this an error with the marketplace api?

**Comment by jbicker** [comment]
No I don't think so. Looks like there is no proper endpoint for that.
@spoenemann

**Comment by spoenemann** [comment]
I'll have a look later this week.

**Comment by spoenemann** [comment]
Created a new issue: https://github.com/eclipse/openvsx/issues/143
