### ISSUE TITLE
Claiming namespace ev3dev

### ISSUE THREAD

**Issue by dlech** [eclipse/open-vsx.org#76]
I am the primary owner/maintainer for [ev3dev.org](https://github.com/ev3dev/). In particular, [this](https://github.com/ev3dev/vscode-ev3dev-browser) is the extension I intend to publish under the ev3dev namespace.

**Comment by jbicker** [comment]
The namespace does not exist yet. 
For more information see: https://github.com/eclipse/openvsx/wiki/Namespace-Access and https://www.npmjs.com/package/ovsx#create-a-namespace

Thanks!

**Comment by dlech** [comment]
Oops, right. This is done now. https://open-vsx.org/extension/ev3dev/ev3dev-browser
