### ISSUE TITLE
Claiming namespace scalameta.metals

### ISSUE THREAD

**Issue by tgodzik** [eclipse/open-vsx.org#83]
Hi I am one of the main contributors of Metals https://github.com/scalameta/metals and it's VS Code extension (https://github.com/scalameta/metals-vscode) and I'd like to add a step to publish to Open VSX.

Is it also possible to add other maintainers? Could I mention them in this ticket and have them added as well?

cc @olafurpg @gabro

**Comment by gabro** [comment]
Adding to the above, I'd like to specify that @tgodzik, @olafurpg and I are also owners of https://github.com/scalameta, hence the namespace claim on `scalameta`

**Comment by olafurpg** [comment]
Ditto

**Comment by spoenemann** [comment]
I added all three of you, but you can now manage namespace members yourself in https://open-vsx.org/user-settings/namespaces.

I removed the extension from https://github.com/open-vsx/publish-extensions. The warning will disappear from https://open-vsx.org/extension/scalameta/metals after you publish a newer version yourself.

**Comment by gabro** [comment]
Thank you @spoenemann!

**Comment by tgodzik** [comment]
Opened up a PR with an additional step for our release https://github.com/scalameta/metals-vscode/pull/359
