### ISSUE TITLE
Claiming namespace [eamodio]

### ISSUE THREAD

**Issue by eamodio** [eclipse/open-vsx.org#9]
I'm the creator of the GitLens extension: https://github.com/eamodio/vscode-gitlens
And many others: https://github.com/eamodio

**Comment by spoenemann** [comment]
Hi @eamodio, thanks for the request. You need to log in to https://open-vsx.org before we can associate the namespace with your user account.

**Comment by eamodio** [comment]
@spoenemann Sorry about that -- I logged in now.

**Comment by andyw8** [comment]
👋 @eamodio have you considered claiming the `gitkraken` namespace? More developers are now using OpenVSX because of new editors such as Cursor, so it would be reassuring to see the organization as the namespace.
