### ISSUE TITLE
Need to unpublish redhat.vscode-quarkus 1.3.0

### ISSUE THREAD

**Issue by fbricon** [eclipse/open-vsx.org#91]
The Red Hat Legal department required us to declare our extensions as "preview" on the VS Code Marketplace. Unsurprisingly, this also makes them "preview" in open-vsx.org. Now [redhat.vscode-quarkus 1.3.0](https://open-vsx.org/extension/redhat/vscode-quarkus/1.3.0) was published before that change, making it by default the "latest" release, even though 3 other "preview" versions have been released since. 
For one, this is not obvious from the open-vsx.org UI. Secondly, you can no longer get automatic updates to the latest release in VSCodium. Updates requires manual intervention.
The simplest way to fix the situation right now is to unpublish redhat.vscode-quarkus 1.3.0. Until https://github.com/eclipse/openvsx/issues/58 is implemented, I need to make the request here. 
Pretty please?

**Comment by spoenemann** [comment]
Is your solution to re-publish 1.3.0 without the `preview` flag?

**Comment by spoenemann** [comment]
Done.

**Comment by fbricon** [comment]
@spoenemann perfect, thanks!
