### ISSUE TITLE
Claiming namespace [runem]

### ISSUE THREAD

**Issue by runem** [eclipse/open-vsx.org#93]
Hi, I would like to claim the namespace `runem` on https://open-vsx.org/.

My publisher name on the marketplace is also `runem` (see https://marketplace.visualstudio.com/publishers/runem) 

My VSCode extension [lit-plugin](https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin) has already been published on [open-vsx](https://open-vsx.org/extension/runem/lit-plugin) (not by me) and I would like to continue updating the extension here. 

Thank you in advance!

**Comment by spoenemann** [comment]
The warning on https://open-vsx.org/extension/runem/lit-plugin will disappear after you have published a new version.
