### ISSUE TITLE
Claiming namespace [nick-rudenko]

### ISSUE THREAD

**Issue by nick-rudenko** [eclipse/open-vsx.org#94]
I was asked in an issue of [my extension](https://marketplace.visualstudio.com/items?itemName=nick-rudenko.back-n-forth) to publish it at open-vsx.org too.
I'd like to claim the namespace `nick-rudenko` (because it's my name obviously :smile:)

Published at open-vsx: https://open-vsx.org/extension/nick-rudenko/back-n-forth

**Comment by spoenemann** [comment]
The back-n-forth extension has no LICENSE. Could you add one? In case you're unsure which one, I'd choose MIT, Apache-2.0 or EPL-2.0.

**Comment by nick-rudenko** [comment]
Added, please check
