### ISSUE TITLE
Make it more prominent how to contribute extensions

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse/open-vsx.org#99]
The instructions how to add an extension to the registry are currently pretty hidden. I am not sure whether possible contributors are aware they can simply add their own.
- I'd expect a top level link like _Missing an extension?_ or _Can I add extensions?_ or similar.
- Instead, instructions are reachable only after two clicks. 
- The section _Publishing Extensions_ should come be before the information on the operator and the source code.
- The bar containing the _About this service_ link is hidden as soon as the user starts scrolling

**Comment by spoenemann** [comment]
See https://github.com/eclipse/openvsx/issues/151 and https://github.com/eclipse/openvsx/issues/142

**Comment by spoenemann** [comment]
Now https://open-vsx.org has a link to the Documentation in its header, so the "How to Publish an Extension" guide is only two well visible clicks away. @JanKoehnlein does that suffice?

**Comment by JanKoehnlein** [comment]
Works for me
